# Generated by Django 4.2.27 on 2026-03-07 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['department', 'title']},
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('western', 'Western School'), ('arabic', 'Arabic School'), ('programming', 'Programming')], default='western', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='api.profile'),
        ),
    ]
