# Generated by Django 6.0.2 on 2026-03-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_enrollment_term_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='add_drop_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='drop_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='term',
            field=models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], default='First Term', max_length=20),
        ),
    ]
