# Generated by Django 6.0.2 on 2026-03-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_started_at_to_quizsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('instructor', 'Instructor'), ('admin', 'Admin'), ('parent', 'Parent'), ('school_admin', 'School Admin'), ('super_admin', 'Super Admin')], default='student', max_length=20),
        ),
    ]
