# Generated by Django 6.0.2 on 2026-03-12 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_school_alter_passwordresetotp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('core', '── Core / Compulsory ──'), ('english_language', 'English Language'), ('mathematics', 'Mathematics'), ('civic_education', 'Civic Education'), ('digital_technologies', 'Digital Technologies / Computer Studies'), ('citizenship_heritage', 'Citizenship and Heritage Studies'), ('entrepreneurship', 'Trade / Entrepreneurship Subject'), ('science', '── Science ──'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('further_mathematics', 'Further Mathematics'), ('agricultural_science', 'Agricultural Science'), ('geography', 'Geography'), ('technical_drawing', 'Technical Drawing'), ('food_nutrition', 'Food and Nutrition'), ('health_education', 'Health Education'), ('physical_health_education', 'Physical and Health Education'), ('arts', '── Humanities / Arts ──'), ('literature_in_english', 'Literature in English'), ('government', 'Government'), ('nigerian_history', 'Nigerian History'), ('christian_religious_studies', 'Christian Religious Studies (CRS)'), ('islamic_religious_studies', 'Islamic Religious Studies (IRS)'), ('visual_arts', 'Visual Arts (Fine Arts)'), ('music', 'Music'), ('french', 'French'), ('arabic', 'Arabic'), ('hausa', 'Hausa'), ('igbo', 'Igbo'), ('yoruba', 'Yoruba'), ('home_management', 'Home Management'), ('catering_craft', 'Catering Craft'), ('commercial', '── Commercial / Business ──'), ('financial_accounting', 'Financial Accounting'), ('commerce', 'Commerce'), ('economics', 'Economics'), ('marketing', 'Marketing'), ('business_studies', 'Business Studies'), ('technical', '── Technology / Technical ──'), ('basic_electronics', 'Basic Electronics'), ('basic_electricity', 'Basic Electricity'), ('metalwork', 'Metalwork'), ('woodwork', 'Woodwork'), ('building_construction', 'Building Construction'), ('auto_mechanics', 'Auto Mechanics'), ('welding_fabrication', 'Welding and Fabrication'), ('computer_studies_ict', 'Computer Studies / ICT'), ('vocational', '── Vocational / Trade ──'), ('solar_installation', 'Solar Panel Installation'), ('fashion_design', 'Fashion Design and Garment Making'), ('livestock_farming', 'Livestock Farming'), ('beauty_cosmetology', 'Beauty and Cosmetology'), ('computer_hardware_repairs', 'Computer Hardware / GSM Repairs'), ('horticulture', 'Horticulture and Crop Production'), ('jss', '── JSS General ──'), ('basic_science', 'Basic Science'), ('basic_technology', 'Basic Technology'), ('social_studies', 'Social Studies'), ('cultural_creative_arts', 'Cultural and Creative Arts'), ('religious_studies', 'Religious Studies (General)')], db_index=True, max_length=50)),
                ('is_auto_assigned', models.BooleanField(default=True, help_text='True = seeded automatically; False = manually set by admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject Assignment',
                'verbose_name_plural': 'Subject Assignments',
                'ordering': ['student', 'subject'],
            },
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='api_profile_role_d4a1db_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='api_profile_departm_e2990b_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='api_profile_role_9e4ac1_idx',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stream',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts / Humanities'), ('commercial', 'Commercial / Business'), ('technical', 'Technical / Vocational'), ('general', 'General')], help_text='Science / Arts / Commercial stream (SSS students only).', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='teacher_type',
            field=models.CharField(blank=True, choices=[('class', 'Class Teacher'), ('subject', 'Subject Teacher')], help_text="Only relevant when role=teacher. 'class' = homeroom teacher; 'subject' = subject specialist.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('western', 'Western Education'), ('arabic', 'Arabic/Islamic Studies'), ('programming', 'Digital Technology')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parent_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('school_admin', 'School Admin'), ('teacher', 'Teacher'), ('non_teaching', 'Non-Teaching Staff'), ('student', 'Student'), ('parent', 'Parent'), ('visitor', 'Visitor')], db_index=True, default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_class',
            field=models.CharField(blank=True, choices=[('jss1a', 'JSS 1A'), ('jss1b', 'JSS 1B'), ('jss1c', 'JSS 1C'), ('jss2a', 'JSS 2A'), ('jss2b', 'JSS 2B'), ('jss2c', 'JSS 2C'), ('jss3a', 'JSS 3A'), ('jss3b', 'JSS 3B'), ('jss3c', 'JSS 3C'), ('sss1_sci', 'SSS 1 Science'), ('sss1_arts', 'SSS 1 Arts'), ('sss1_com', 'SSS 1 Commercial'), ('sss2_sci', 'SSS 2 Science'), ('sss2_arts', 'SSS 2 Arts'), ('sss2_com', 'SSS 2 Commercial'), ('sss3_sci', 'SSS 3 Science'), ('sss3_arts', 'SSS 3 Arts'), ('sss3_com', 'SSS 3 Commercial'), ('arabic_beginners', 'Arabic Beginners'), ('arabic_elementary', 'Arabic Elementary'), ('arabic_intermediate', 'Arabic Intermediate'), ('arabic_advanced', 'Arabic Advanced'), ('quran_hifz_1', "Qur'an Hifz Level 1"), ('quran_hifz_2', "Qur'an Hifz Level 2"), ('quran_hifz_3', "Qur'an Hifz Level 3"), ('islamic_studies_1', 'Islamic Studies 1'), ('islamic_studies_2', 'Islamic Studies 2'), ('islamic_studies_3', 'Islamic Studies 3'), ('prog_beginners', 'Programming Beginners'), ('prog_elementary', 'Programming Elementary'), ('prog_intermediate', 'Programming Intermediate'), ('prog_advanced', 'Programming Advanced'), ('web_dev_1', 'Web Development 1'), ('web_dev_2', 'Web Development 2'), ('data_science', 'Data Science'), ('cybersecurity', 'Cybersecurity')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role', 'department'], name='api_profile_role_c67045_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role', 'student_class'], name='api_profile_role_ac2ec6_idx'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instructor_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_archived',
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('student', 'subject')},
        ),
    ]
