# Generated by Django 6.0.3 on 2026-03-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_subjectassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_class',
            field=models.CharField(blank=True, choices=[('jss1a', 'JSS 1A'), ('jss1b', 'JSS 1B'), ('jss1c', 'JSS 1C'), ('jss2a', 'JSS 2A'), ('jss2b', 'JSS 2B'), ('jss2c', 'JSS 2C'), ('jss3a', 'JSS 3A'), ('jss3b', 'JSS 3B'), ('jss3c', 'JSS 3C'), ('sss1_sci', 'SSS 1 Science'), ('sss1_arts', 'SSS 1 Arts'), ('sss1_com', 'SSS 1 Commercial'), ('sss2_sci', 'SSS 2 Science'), ('sss2_arts', 'SSS 2 Arts'), ('sss2_com', 'SSS 2 Commercial'), ('sss3_sci', 'SSS 3 Science'), ('sss3_arts', 'SSS 3 Arts'), ('sss3_com', 'SSS 3 Commercial'), ('ibtidaai_1', 'الصف الأول الابتدائي'), ('ibtidaai_2', 'الصف الثاني الابتدائي'), ('ibtidaai_3', 'الصف الثالث الابتدائي'), ('ibtidaai_4', 'الصف الرابع الابتدائي'), ('ibtidaai_5', 'الصف الخامس الابتدائي'), ('ibtidaai_6', 'الصف السادس الابتدائي'), ('mutawassit_1', 'الصف الأول المتوسط'), ('mutawassit_2', 'الصف الثاني المتوسط'), ('mutawassit_3', 'الصف الثالث المتوسط'), ('thanawi_1', 'الصف الأول الثانوي'), ('thanawi_2', 'الصف الثاني الثانوي'), ('thanawi_3', 'الصف الثالث الثانوي'), ('ai_ml_beginner', 'AI & ML — Beginner'), ('ai_ml_junior', 'AI & ML — Junior'), ('ai_ml_intermediate', 'AI & ML — Intermediate'), ('ai_ml_advanced', 'AI & ML — Advanced'), ('data_science_beginner', 'Data Science — Beginner'), ('data_science_junior', 'Data Science — Junior'), ('data_science_intermediate', 'Data Science — Intermediate'), ('data_science_advanced', 'Data Science — Advanced'), ('scratch_beginner', 'Scratch — Beginner'), ('scratch_junior', 'Scratch — Junior'), ('scratch_intermediate', 'Scratch — Intermediate'), ('scratch_advanced', 'Scratch — Advanced'), ('frontend_beginner', 'Frontend — Beginner'), ('frontend_junior', 'Frontend — Junior'), ('frontend_intermediate', 'Frontend — Intermediate'), ('frontend_advanced', 'Frontend — Advanced'), ('backend_beginner', 'Backend — Beginner'), ('backend_junior', 'Backend — Junior'), ('backend_intermediate', 'Backend — Intermediate'), ('backend_advanced', 'Backend — Advanced'), ('ai_automation_beginner', 'AI Automation — Beginner'), ('ai_automation_junior', 'AI Automation — Junior'), ('ai_automation_intermediate', 'AI Automation — Intermediate'), ('ai_automation_advanced', 'AI Automation — Advanced')], db_index=True, max_length=30, null=True),
        ),
    ]
