# Generated by Django 6.0.2 on 2026-03-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sync_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_class',
            field=models.CharField(blank=True, choices=[('JSS1', 'JSS 1'), ('JSS2', 'JSS 2'), ('JSS3', 'JSS 3'), ('SS1', 'SS 1'), ('SS2', 'SS 2'), ('SS3', 'SS 3'), ('ibtidaahi', 'Ibtidaahi'), ('idaady', 'Idaady'), ('thanawy', 'Thanawy'), ('web_dev', 'Web Dev'), ('ai_ml', 'AI & ML'), ('ai_automation', 'AI Automation'), ('scratch', 'Scratch')], max_length=20, null=True),
        ),
    ]
