# Generated by Django 6.0.2 on 2026-03-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_quiz_options_alter_profile_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, help_text='Automatically generated unique student identifier', max_length=20, null=True, unique=True),
        ),
    ]
