# Generated by Django 6.0.2 on 2026-03-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instructor_type',
            field=models.CharField(blank=True, choices=[('subject', 'Subject Instructor'), ('class', 'Class Instructor')], help_text='Only applicable if role is instructor', max_length=20, null=True),
        ),
    ]
