# Generated by Django 6.0.3 on 2026-03-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile_class_section_alter_profile_stream_and_more'),
    ]

    operations = [
    ]
