# Generated by Django 6.0.3 on 2026-07-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20260319_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('school_admin', 'School Admin'), ('teacher', 'Teacher'), ('non_teaching', 'Non-Teaching Staff'), ('student', 'Student'), ('parent', 'Parent'), ('visitor', 'Visitor')], default='student', help_text='Primary role of the user — determines permissions and UI access.', max_length=20, verbose_name='role'),
        ),
    ]
