# Generated by Django 6.0.3 on 2026-07-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-date_earned']},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-due_date']},
        ),
        migrations.AlterModelOptions(
            name='instructorassignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={'ordering': ['-submitted_at']},
        ),
    ]
