# Generated by Django 6.0.3 on 2026-07-17 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_feepayment_paystack_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this course belongs to. Null for global/system courses.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.school'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this profile belongs to. Null for super_admin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='api.school'),
        ),
        migrations.AddField(
            model_name='school',
            name='allow_arabic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='allow_programming',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='allow_western',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the current subscription ends.', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='max_courses',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='school',
            name='max_students',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='school',
            name='max_teachers',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='school',
            name='owner_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='owner_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='plan',
            field=models.CharField(choices=[('free', 'Free Trial'), ('starter', 'Starter'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL-friendly identifier, e.g. 'al-furqan'", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='subscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_id',
            field=models.CharField(blank=True, default='', help_text='Paystack customer/plan reference.', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the free trial expires.', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this user belongs to. Null for super_admin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.school'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('paystack_customer_code', models.CharField(blank=True, default='', max_length=100)),
                ('paystack_subscription_code', models.CharField(blank=True, default='', max_length=100)),
                ('paystack_plan_code', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in NGN', max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
