version: "3.9"

services:
  web:
    build: ../backend
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=nexuslms.settings.production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: ../backend
    command: celery -A nexuslms worker -l info
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:7
    restart: always
